#!/usr/bin/env bash
# Bash Script to install and configure nginx server

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

sudo sed -i s/80 default_server;/80 default_server;\n\troot \/var\/www\/html;/g /etc/nginx/sites-available/default

sudo kill -s HUP $(pgrep nginx)

echo "Hello World!" | sudo tee /var/www/html/index.html
