#!/usr/bin/env bash
# Bash Script to install and configure nginx server

sudo apt update

sudo apt install nginx -y

sudo sed s/80 default_server;/80 default_server;\n\troot \/var\/www\/html;/g /etc/nginx/sites-available/default

sudo kill -s HUP $(pgrep nginx)

echo "Hello World!" | sudo tee /var/www/html/index.html
