#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo nginx

sudo sed -i 's/80 default_server;/80 default_server;\n\troot \/var\/www\/html;/g' /etc/nginx/sites-available/default

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.x

sudo truncate -s 0 /var/www/html/index.nginx-debian.html

echo -e "Hello World!" | sudo tee /var/www/html/index.index.nginx-debian.html

sudo touch redirect_config

echo 'server {
    listen 80;

    location /redirect_me {
        return 301 http://google.com/;
    }
}' | sudo tee /etc/nginx/sites-available/redirect_config

sudo ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled

sudo nginx -s stop
sudo nginx
