#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

sudo sed -i s/80 default_server;/80 default_server;\n\troot \/var\/www\/html;/g /etc/nginx/sites-available/default

redirect='s/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}/'

sudo sed -i "$redirect" /etc/nginx/sites-available/default

sudo kill -s HUP $(pgrep nginx)

echo "Hello World!" | sudo tee /var/www/html/index.html
