#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

sudo sed s/80 default_server;/80 default_server;\n"$(printf '\t')"root /var/www/html;/g /etc/nginx/sites-available/default

cp /var/www/html/index.index.nginx-debian.html /var/www/html/index.index.nginx-debian.x

echo -e "Hello World!" > /var/www/html/index.index.nginx-debian.html

sudo touch redirect_config

echo 'server {
    listen 80;

    location /redirect_me {
        return 301 http://google.com/;
    }
}' | sudo tee /etc/nginx/sites-available/redirect_config

sudo ln -s etc/nginx/sites-available/redirect_config etc/nginx/sites-enabled

sudo service nginx restart
