#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.x

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\	rewrite ^/redirect_me https://www.google.com' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/err404.html

sed -i '25i\	error_page 404 /err404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
