#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo nginx

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.x

sudo truncate -s 0 /var/www/html/index.nginx-debian.html

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '24i\	rewrite ^/redirect_me https://www.google.com' /etc/nginx/sites-available/default

sudo touch /var/www/html/err404.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/err404.html

sudo sed -i '25i\	error_page 404 /err404.html;' /etc/nginx/sites-available/default

sudo nginx -s stop
sudo nginx
