#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

sudo sed -i 's/80 default_server;/80 default_server;\n\troot \/var\/www\/html;/g' /etc/nginx/sites-available/default

sudo sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t}/' /etc/nginx/sites-available/default

sudo kill -s HUP $(pgrep nginx)

echo "Hello World!" | sudo tee /var/www/html/index.html
