#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Hi
i=1
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
