#!/usr/bin/env bash
# Bash script that configures the container
sudo apt update -y -qq
sudo apt install nginx -y
sudo systemctl start nginx
sudo sed -i 's/user www-data;/#user www-data;\nuser nginx;/' /etc/nginx/nginx.conf
sudo systemctl restart nginx
